TopFoods/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from pathlib import Path
import environ

env = environ.Env()
BASE_DIR = Path(__file__).resolve().parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

urlpatterns = [
    path(env('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path('getFoods/', include("getFoods.urls")),
]

getFoods/urls.py
from django.urls import path

from . import views, api

app_name = "getFoods"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("plan_trip", views.plan_trip, name="plan_trip"),
    path("itinerary", views.itinerary, name="itinerary"),
    path("register", views.register, name="register"),
    path("delete/<int:id>", views.delete, name='delete'),
    path("get_cities/<str:country>", api.get_cities, name='get_cities'),
    path("get_top_foods", api.get_top_foods, name='get_top_foods'),
    ]

getFoods/models.py
from django.db import models
# from smart_selects.db_fields import ChainedForeignKey
from cities_light.models import Country, City

class Users(models.Model):
    username = models.CharField(max_length=100)
    destinations = models.ManyToManyField(City, blank=True)

    def __str__(self):
        return f"{self.username}"

class Food(models.Model):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    search_name = models.CharField(max_length=100, null=True)
    display_name = models.CharField(max_length=100, null=True)
    descr = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return f"{self.display_name}"

class Restaurant(models.Model):
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    food_name = models.ForeignKey(Food, on_delete=models.SET_NULL, null=True)
    resto_name = models.CharField(max_length=100, null=True, blank=True)     
    resto_latitude = models.FloatField(null=True, blank=True) 
    resto_longitude = models.FloatField(null=True, blank=True) 
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return f"{self.resto_name}"

getFoods/forms.py
from django import forms
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.core.exceptions import ValidationError  
from django.forms.fields import EmailField  
from django.forms.forms import Form  


#learned from https://www.javatpoint.com/django-usercreationform
class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", max_length=60)
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput)

    #single field validations come from clean_FIELDNAME()
    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        existing_user = User.objects.filter(username = username)  
        #if number of acounts with username > 0
        if existing_user.count():  
            raise ValidationError("User Already Exist")  
        return username  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        existing_email = User.objects.filter(email=email)  
        if existing_email.count():  
            raise ValidationError("Email Already Exist")  
        return email  
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Passwords don't match")  
        return password2  
  
    def save(self):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        return user  

getFoods/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Users, Food
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm  
from .forms import RegisterForm  
from cities_light.models import Country, City
from .utils.functions import getGoogleApiKeyFrontend
 #logger.info("----- info: %s", value)





def index(request):
    return HttpResponseRedirect(reverse('getFoods:login'))



# --------------------------- SECTION FOR LOGIN/OUT ---------------------------------------

def register(request):
    """
    If user's first time to site (GET), renders registration page.
    Else (POST), uses the info user inputted to create and register new user. 
    """

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        #if valid, create user and redirect to login 
        if form.is_valid():
            #creates user for django admin
            form.save() 
            #create user for Users model
            username = form.cleaned_data.get('username') 
            user = Users.objects.create(username = username)
            messages.success(request, "Account created.")
            return HttpResponseRedirect(reverse('getFoods:login'))
        #if not valid, go to register page again with same form
        else:
            messages.error(request, "Please change inputs and try again.")
            return render(request, "getFoods/register.html", {
                    'RegisterForm': form})
    
    #Else create new form and get user to register
    form = RegisterForm()
    return render(request, "getFoods/register.html", {'RegisterForm': form})




def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)

        if user: 
            login(request, user)
            #set session cookie
            request.session['my_username'] = username
            return HttpResponseRedirect(reverse('getFoods:plan_trip'))
        else:
            return render(request, "getFoods/login.html",
                {'message': "Wrong username or password."})

    #go to login page if new to site
    return render(request, "getFoods/login.html")




def logout_view(request):
    logout(request)
    try:
        del request.session['username']
    except KeyError:
        pass
    return render(request, "getFoods/login.html", {'message': "Logged out."})






#---------------------------- SECTION FOR PLAN_TRIP.HTML -----------------------------------------

def plan_trip(request):
    """
    If POST, it means new country is submitted, add the country.
    Else, it is the user's first time on the page so direct them to html. 
    """

    user = Users.objects.get(username = request.session.get('my_username'))

    if request.method == "POST":
        requested_city = request.POST['add-city']
        #check for only contains digits (city id), against sql insert hacking
        if requested_city.isnumeric():
            new_dest = City.objects.get(id = requested_city)
            #don't check if new_dest exists in user.destination, django checks
            user.destinations.add(new_dest)

    return render(request, "getFoods/plan_trip.html", {
        'user': user,
        'countries': Country.objects.all(),
        'cities': City.objects.all(),
        })




def delete(request, id):
    """
    Delete destination from user.destinations.
    """

    user = Users.objects.get(username = request.session.get('my_username'))
    destination = user.destinations.get(id = id)
    user.destinations.remove(destination)
    return HttpResponseRedirect(reverse('getFoods:plan_trip'))

    


    

#--------------------------- SECTION FOR ITINERARY.HTML ------------------------------------------

def itinerary(request):
    """
    Leads user to Itinerary page after submitting Plan Trip page.
    """

    user = Users.objects.get(username = request.session.get('my_username'))
    gmap_frontend_key = getGoogleApiKeyFrontend()
    return render(request, "getFoods/itinerary.html", {
        'user': user,
        'frontend_api_key': gmap_frontend_key
        })





   

getFoods/templates/getFoods/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
        <head>
            <title>{% block title %}{% endblock title %}</title>
            <link rel="stylesheet" href="{% static 'css/style.css' %}">
            {% block js %}{% endblock js %}
        </head>
        <body>
            {% block content %}{% endblock content %}
        </body>
    </html>

getFoods/templates/getFoods/itinerary.html
{% extends "getFoods/base.html" %}

{% block title %}Your Eatinerary{% endblock title %}

{% block js %}
<!-- This script creates html code for all foods and creates maps -->
<script>
    //This function creates maps and adds pins for all restaurants
    async function initMap(cityObject, cityName) {
        // Use location of random resto as location of city
        const position = {
            lat: cityObject[0]["resto_latitude"],
            lng: cityObject[0]["resto_longitude"]
        };

        const { Map } = await google.maps.importLibrary("maps");
        const { AdvancedMarkerElement } = await google.maps.importLibrary("marker");

        gMap = new Map(document.getElementById(cityName + "Map"), {
            zoom: 12,
            center: position,
            mapId: 'cityName + "Map"',
            mapTypeControl: false,
            streetViewControl: false

        });

        for (const food of cityObject) {
            const curr_position = {
                lat: food["resto_latitude"],
                lng: food["resto_longitude"]
            };

            const marker = new AdvancedMarkerElement({
                map: gMap,
                position: curr_position,
                title: food["display_name"]
            });
        }
    }

    document.addEventListener('DOMContentLoaded', function () {
        fetch('/getFoods/get_top_foods')
            .then((response) => {
                return response.json();
            })
            .then(data => {
                (g => { var h, a, k, p = "The Google Maps JavaScript API", c = "google", l = "importLibrary", q = "__ib__", m = document, b = window; b = b[c] || (b[c] = {}); var d = b.maps || (b.maps = {}), r = new Set, e = new URLSearchParams, u = () => h || (h = new Promise(async (f, n) => { await (a = m.createElement("script")); e.set("libraries", [...r] + ""); for (k in g) e.set(k.replace(/[A-Z]/g, t => "_" + t[0].toLowerCase()), g[k]); e.set("callback", c + ".maps." + q); a.src = `https://maps.${c}apis.com/maps/api/js?` + e; d[q] = f; a.onerror = () => h = n(Error(p + " could not load.")); a.nonce = m.querySelector("script[nonce]")?.nonce || ""; m.head.append(a) })); d[l] ? console.warn(p + " only loads once. Ignoring:", g) : d[l] = (f, ...n) => r.add(f) && u().then(() => d[l](f, ...n)) })
                    ({ key: "{{ frontend_api_key }}", v: "weekly" });


                innerHtml = ""
                //create html code for every city and add map after 5 foods listed
                for (let i = 0; i < data.length; i++) {
                    cityObject = data[i];
                    cityName = cityObject[0]["city_name"];
                    innerHtml += "<div class='city'>" + "<div class='city-text'>" + "<h3 class=\"city-name-title\">" + cityName + "</h3>";

                    for (const food of cityObject) {
                        innerHtml += 
                            "<div class='one-food'>" 
                            + "<div class=\"food-display-name\">" + food['display_name'] + "</div>"
                            + "<div class=\"food-descr\">" + food['food_descr'] + "</div>"
                            + "Try this dish at: " 
                            + "<span class=\"try-food-at\">" + food['resto_name'] + "</span>"
                            + "</div>";
                    }

                    innerHtml += "</div>" + "<div id='" + cityName
                        + "Map' class=\"city-map\"></div>"

                    // Initialize map
                    initMap(cityObject, cityName);

                    innerHtml += "</div>" //end div for city's div
                }

                document.querySelector('#all-destinations').innerHTML = innerHtml;
            })
    });
</script>
{% endblock js %}

{% block content %}
<div class="itinerary-container">
    <a href="{% url 'getFoods:plan_trip' %}" id="go-back">← Go back</a>
    <h1>Travel Eatinerary</h1>
    <div id="all-destinations">Loading...</div>
    <a href="{% url 'getFoods:logout' %}" id="logout-link">Log Out &#128075</a>
</div>
{% endblock content %}

getFoods/templates/getFoods/login.html
{% extends "getFoods/base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="loginRegister-container">
    <h1 style="margin: 1rem 0; color:green;">Travel Eatinerary</h1>

    <div class="login-text">
        {% if message %}
            <p style="color:grey;">{{ message }}</p>
        {% endif %}
        
        <div class="side-lines">
            <span id="side-line-text">Login</span>
        </div>

        <form method="post" action="{% url 'getFoods:login' %}">
            {% csrf_token %}
            <input type="text" name="username" id="username" placeholder=" Username"/>
            <br>
            <input type="password" name="password" id="password" placeholder=" Password"/>
            <br>
            <input class="submit-btn" type="submit" value="Log In">
        </form>
        <p id="login-to-register">New here?</p>
        <a href="{% url 'getFoods:register' %}" class="login-reg-link">Sign Up</a>
    </div>
</div>
{% endblock content %}

getFoods/templates/getFoods/planTrip.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>World Food Tour!</title>
    </head>
    <body>
        <h1>{{ user.username }}'s Food Tour!</h1>
        <p>How it works: Select the countries you will be travelling to and add them to the list below. Press submit and enjoy a guide for local cuisines to try on your trip!</p>

        <!-- # means stay on same page -->
        <form method="post" action='#'>
            {% csrf_token %}
            <label for="addCountry">Next Country:</label>
            <select name="newCountry">
                {% for country in countriesNotSelected %}
                    <option value="{{ country }}">{{ country }}</option>
                {% endfor %}
            </select>
            <br>
            <button type="submit">Add</button>
            <p>Current countries selected:</p>
            <ul>
                {% for country in countriesSelected %}
                    <li>{{ country.countryName}} <button>delete</button></li>
                {% endfor %}
            </ul>
            <input type="checkbox">
            <label for="exampleCheck">I want to receive a copy of this guide in my email.</label>
            <br>
            <button type="submit" formaction="{% url 'getFoods:itinerary'%}">Get Your Tour</button>
            <br>
        </form>
        <a href="{% url 'getFoods:logout' %}">Log Out</a>
    </body>
</html>

getFoods/templates/getFoods/plan_trip.html
{% extends "getFoods/base.html" %}

{% block title %}World Food Tour{% endblock title %}

{% block js %}
<!-- JS to populate city drop down selector once country selected. -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        //only execute when country selected
        document.getElementById("add-country").addEventListener("change", function () {
            const country = document.querySelector('#add-country').value;
            fetch(`/getFoods/get_cities/${country}`)
                .then((response) => response.json())
                .then(data => {
                    innerHtml = '<option value="">City</option>';
                    //iterate over cities to add add city name as select value
                    for (let i = 0; i < data.length; i++) {
                        let cityObject = data[i];
                        cityName = cityObject['fields']['name'];
                        //pk field gives city id
                        cityId = cityObject['pk'];
                        innerHtml += "<option value=\"" + cityId + "\">" + cityName + "</option>"
                    }
                    document.querySelector('#add-city').innerHTML = innerHtml;
                })
        })
    });
</script>
{% endblock js %}

{% block content %}
<div class="plan-trip-page-container">
    <div id="plan-trip-green">
        <h1 style="margin: 3rem 0;">Plan Your Trip</h1>
        <p>Select the cities you will be travelling to and receive a guide of local cuisines to try on your trip!</p>
        <p style="font-size:63%;padding:0.5rem 0 0;">* Currently only these countries will work: Canada, Japan, Taiwan, France, Italy, Ireland, USA, Spain, Greece, Turkey, Mexico, UK, Austria, Thailand.</p>

        <!-- '' means go to same page -->
        <form method="post" action='' id="plan-trip-form">
            {% csrf_token %}
            <!-- select element for country -->
            <select name="add-country" id="add-country" required>
                <!-- this empty option tag is for "Country" display, the rest will be filled from js -->
                <option value="">Country</option> 
                {% for new_country in countries %}
                <option value="{{ new_country }}">{{ new_country }}</option>
                {% endfor %}
            </select>

            <!-- select element for city -->
            <select name="add-city" id="add-city" required>
                <option value="">City</option>
                <!-- don't need other options, js innerHtml will fill items -->
            </select>
            <button type="submit" id="add-btn">Add</button>
        </form>
    </div>

    <div id="plan-trip-white">
        <!-- list current destinations chosen with option to delete -->
        <div id="plan-trip-white-text">
            <p style="text-align: center;">Current destinations selected:</p>
            <ul id="selected-dest">
                {% for destination in user.destinations.all %}
                <li>{{ destination.name }}, {{ destination.country.name }}
                    <a href="delete/{{destination.id}}" id="delete-btn">Delete</a>
                    {% endfor %}
            </ul>

            <!-- submit or logout -->
            <div id="get-tour-container">
                <a href="{% url 'getFoods:itinerary'%}">
                    <button class="submit-btn">Get Your Tour</button>
                </a>
                <a href="{% url 'getFoods:logout' %}" class="login-reg-link">Log Out</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

getFoods/templates/getFoods/register.html
{% extends "getFoods/base.html" %}

{% block title %}Register{% endblock title %}

{% block content %}
<div class="loginRegister-container">
    <h1 style="margin-bottom: 2rem;">Sign Up</h1>
    <div class="register-text">
        {% if message %}
            <div>{{ message }}</div>
        {% endif %}
        <form id="register-form" method="post">
            {% csrf_token %}
            <table>
                {{ RegisterForm.as_table}}
            </table>
            <input type="submit" name="submit" class="submit-btn" value="Register"/>
        </form>
        <a href="{% url 'getFoods:login' %}" class="login-reg-link">Back to Login</a>
    </div>
</div>
{% endblock content %}